name: DisasterShield
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  carousel_slider: ^5.0.0
  flutter_native_splash: ^2.4.6
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image1.png
    - assets/image2.png
    - assets/image3.png
    - assets/logo.png
    - assets/icon.png
    - assets/pnp.png
    - assets/bfp.png
    - assets/doh.png
    - assets/ndrrmc.png   
    - assets/pagasa.png
    - assets/pcg.png
    - assets/phivolcs.png
